import { NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { guestCreateSchema } from "@/lib/validation/schemas";

const DUPLICATE_MOBILE_MESSAGE =
  "A guest with this mobile number already exists for this event.";

/**
 * POST /api/events/[id]/guests — add a guest to an event.
 * A unique Guest_Token is generated by the DB default.
 * Duplicate mobile within the same event is rejected with a friendly message.
 * Requirements: 3.1, 3.2, 3.4, 4.1
 */
export async function POST(
  request: Request,
  { params }: { params: { id: string } },
) {
  const supabase = createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json().catch(() => null);
  const parsed = guestCreateSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Validation failed", fields: parsed.error.flatten().fieldErrors },
      { status: 400 },
    );
  }

  const { firstName, lastName, mobile, predictedGuests, familyRelation } =
    parsed.data;

  const { data, error } = await supabase
    .from("guest")
    .insert({
      event_id: params.id,
      first_name: firstName,
      last_name: lastName,
      mobile,
      predicted_guests: predictedGuests,
      family_relation: familyRelation ?? null,
    })
    .select("id")
    .single();

  if (error) {
    if (error.code === "23505") {
      return NextResponse.json(
        { error: DUPLICATE_MOBILE_MESSAGE },
        { status: 409 },
      );
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ id: data.id }, { status: 201 });
}
